### ISSUE TITLE
Multinomial regression

### ISSUE THREAD

**Issue by bdeonovic** [lindahua/Regression.jl#14]
I'm not quite sure I understand how multinomial regression works. Can you explain a bit about the structure of the data matrix `X` and response `y`? Also, in the example for multinomial logistic regression the `W_est` does not seem anywhere near the true simulated `W`, even if I increase sample size `n` to 10000, is this expected? 

In particular I am trying to fit a multinomial logistic regression to lagged response variables, how do I pass those in?

**Comment by bdeonovic** [comment]
Is this package still supported? The documentation seems very lacking. I am interested in multinomial regression, but I am unsure about what the output from this package is. Which category is used as base category? What does the solution correspond to?

**Comment by WenjieZ** [comment]
For multinomial logistic regression, the parameter `W` is not unique. For instance, `W` and `W+1` yield the same value for the loss function. You may want to check first whether the loss function is correctly minimized or whether the classification is correctly done. 

Ref: http://spark.apache.org/docs/latest/mllib-linear-methods.html

**Comment by bdeonovic** [comment]
Can anyone help me figure out how to get similar results as R's multinomial regression? My data can be found here:

https://www.dropbox.com/s/1h7uns55t34c8fr/timeseries.txt?dl=0

Here is how I called R:

`````` R
library(nnet)
data <- read.table("Dropbox/scripts/timeseries.txt",header=TRUE)
multinom(y~X1+X2,data)
```R
# weights:  12 (6 variable)
initial  value 10985.024274 
iter  10 value 10438.503738
final  value 10438.503529 
converged
Call:
multinom(formula = y ~ X1 + X2, data = data)

Coefficients:
  (Intercept)        X1        X2
2   0.4877087 0.2588725 0.2762119
3   0.4421524 0.5305649 0.3895339

Residual Deviance: 20877.01 
AIC: 20889.01 
``````

using Julia my first attempt is:

``` julia
using DataFrames
using Regression
import Regression: solve, Options, predict
dat = readtable("timeseries.txt", separator='\t')
X = convert(Matrix{Float64},dat[:,2:3])'
y = convert(Vector{Int64},dat[:,1])

ret = solve(mlogisticreg(X,y,3), reg=ZeroReg(),  options=Options(verbosity=:iter))
ret.sol
3x2 Array{Float64,2}:
 -0.591374  -0.442353
  0.17479    0.168595
  0.416584   0.273758
```

Note the response variables are just the discretized time-lagged response i.e. 

``` julia
julia> dat[1:3,:]
3x3 DataFrames.DataFrame
| Row | y | X1 | X2 |
|-----|---|----|----|
| 1   | 3 | 1  | 0  |
| 2   | 3 | 0  | 1  |
| 3   | 1 | 0  | 1  |
```

for row 2 you can see that the response (0, 1) means the previous observation was a 3. Similarly (1,0) means previous observation was a 2 and (0,0) means previous observation was a 1.
