### ISSUE TITLE
Cannot be loaded

### ISSUE THREAD

**Issue by Ronggui** [lindahua/Regression.jl#4]
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.0-prerelease+1864 (2014-03-06 05:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 6438683* (7 days old master)
|__/                   |  i686-w64-mingw32

julia> using Regression
ERROR: AbstractPDMat not defined
while loading C:\Users\.julia\v0.3\Regression\src\linearreg.jl, in expre
ssion starting on line 217
while loading C:\Users\.julia\v0.3\Regression\src\Regression.jl, in expr
ession starting on line 29

**Comment by lindahua** [comment]
It has been completely rewritten now.
